fizzbuzz課題の提出
kimura-ryoji/labot-js-task pull request #1
Opened 2020-02-04 09:31 UTC by kimura-ryoji

2020-02-04 09:42 UTC, Yuzunoha requested changes

2020-02-04 09:42 UTC, Yuzunoha commented on fizzbuzz/index.js
> +    }}
おしい `}}` ここはさすがにちゃんと改行しましょう

2020-02-06 02:53 UTC, kimura-ryoji commented on fizzbuzz/index.js
> +    }}
4351493d627868f1137e51aaaed44ed9843d77d6
このコミットで修正しました。

2020-02-06 02:55 UTC, Yuzunoha approved these changes
いいと思います！承認しました！！

2020-02-06 02:55 UTC, merged